destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/nP_4_4_0-pdf"
port: 4011
output: pdf
product: netPrefect
print_title: netPrefect documentation
print_subtitle: version 4.0.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true